// Generated by codegen from wit/todos.wit — do not edit by hand.

using System.Net.Http.Json;
using System.Text.Json.Serialization;

namespace DamascusUI.Gen;

public record Todo(
    uint Id,
    string Title,
    bool Done
);

public record CreateTodo(
    string Title
);

public record UpdateTodo(
    string? Title,
    bool? Done
);

public class TodosClient(HttpClient http)
{
    public async Task<Todo[]> ListTodos()
    {
        var res = await http.GetAsync("/api/todos");
        return (await res.Content.ReadFromJsonAsync<Todo[]>())!;
    }

    public async Task<Todo> CreateTodo(CreateTodo createTodo)
    {
        var res = await http.PostAsync("/api/todos", JsonContent.Create(createTodo));
        return (await res.Content.ReadFromJsonAsync<Todo>())!;
    }

    public async Task<Todo> UpdateTodo(uint id, UpdateTodo updateTodo)
    {
        var res = await http.PutAsync($"/api/todos/{id}", JsonContent.Create(updateTodo));
        return (await res.Content.ReadFromJsonAsync<Todo>())!;
    }

    public async Task DeleteTodo(uint id)
    {
        await http.DeleteAsync($"/api/todos/{id}");
    }
}
