// Generated by codegen from wit/todos.wit — do not edit by hand.

export interface Todo {
  id: number;
  title: string;
  done: boolean;
}

export interface CreateTodo {
  title: string;
}

export interface UpdateTodo {
  title: string | null;
  done: boolean | null;
}

const BASE = "http://127.0.0.1:3001";

export function createTodosClient() {
  return {
    async listTodos(): Promise<Todo[]> {
      const res = await fetch(`${BASE}/api/todos`, { method: "GET" });
      if (!res.ok) throw new Error(res.statusText);
      return res.json();
    },

    async createTodo(createTodo: CreateTodo): Promise<Todo> {
      const res = await fetch(`${BASE}/api/todos`, {
        method: "POST",
        body: JSON.stringify(createTodo),
        headers: { "Content-Type": "application/json" },
      });
      if (!res.ok) throw new Error(res.statusText);
      return res.json();
    },

    async updateTodo(id: number, updateTodo: UpdateTodo): Promise<Todo> {
      const res = await fetch(`${BASE}/api/todos/${id}`, {
        method: "PUT",
        body: JSON.stringify(updateTodo),
        headers: { "Content-Type": "application/json" },
      });
      if (!res.ok) throw new Error(res.statusText);
      return res.json();
    },

    async deleteTodo(id: number): Promise<void> {
      const res = await fetch(`${BASE}/api/todos/${id}`, { method: "DELETE" });
      if (!res.ok) throw new Error(res.statusText);
    },
  };
}
