// Generated by `damascus codegen` from wit/todos.wit — do not edit.

using System.Net.Http.Json;
using System.Text.Json.Serialization;

namespace DamascusUI.Gen;

public record Todo(
    uint Id,
    string Title,
    bool Done
);

public record CreateTodo(
    string Title
);

public record UpdateTodo(
    string? Title,
    bool? Done
);

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(Todo))]
[JsonSerializable(typeof(Todo[]))]
[JsonSerializable(typeof(CreateTodo))]
[JsonSerializable(typeof(UpdateTodo))]
public partial class TodosJsonContext : JsonSerializerContext { }

public class TodosClient(HttpClient http)
{
    private static readonly TodosJsonContext _json = TodosJsonContext.Default;

    public async Task<Todo[]> ListTodos()
    {
        var res = await http.GetAsync("/api/todos");
        return (await res.Content.ReadFromJsonAsync(_json.TodoArray))!;
    }

    public async Task<Todo> CreateTodo(CreateTodo createTodo)
    {
        var res = await http.PostAsync("/api/todos", JsonContent.Create(createTodo, _json.CreateTodo));
        return (await res.Content.ReadFromJsonAsync(_json.Todo))!;
    }

    public async Task<Todo> UpdateTodo(uint id, UpdateTodo updateTodo)
    {
        var res = await http.PutAsync($"/api/todos/{id}", JsonContent.Create(updateTodo, _json.UpdateTodo));
        return (await res.Content.ReadFromJsonAsync(_json.Todo))!;
    }

    public async Task DeleteTodo(uint id)
    {
        await http.DeleteAsync($"/api/todos/{id}");
    }
}
